# Autogenerated at 2021-07-09T00:54:41.919641
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='2.4.0-0.0.pre'
FLUTTER_WINDOWS_ARCHIVE='dev/windows/flutter_windows_2.4.0-0.0.pre-dev.zip'
FLUTTER_WINDOWS_SHA256='725315a69b4ed99feeae76c6681ebeeba618957bfe45125b7fb6d292a0aeafc1'
FLUTTER_LINUX_VERSION='2.4.0-0.0.pre'
FLUTTER_LINUX_ARCHIVE='dev/linux/flutter_linux_2.4.0-0.0.pre-dev.tar.xz'
FLUTTER_LINUX_SHA256='6d9593935d874e9e95cda99b7f72028420aed1cefa365ca87e58765e01860f3a'
FLUTTER_MACOS_VERSION='2.4.0-0.0.pre'
FLUTTER_MACOS_ARCHIVE='dev/macos/flutter_macos_2.4.0-0.0.pre-dev.zip'
FLUTTER_MACOS_SHA256='45bab8cb02509bd6256336deffa904aec34515ee71d4f42495cb51ea478f7183'
