# Autogenerated at 2024-02-17T20:34:18.141853
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='3.19.0'
FLUTTER_WINDOWS_ARCHIVE='stable/windows/flutter_windows_3.19.0-stable.zip'
FLUTTER_WINDOWS_SHA256='713a10125edb7a253b5d626a6ebd8afdcf4a9c82cb34310ec18783da682b98f3'
FLUTTER_LINUX_VERSION='3.19.0'
FLUTTER_LINUX_ARCHIVE='stable/linux/flutter_linux_3.19.0-stable.tar.xz'
FLUTTER_LINUX_SHA256='4cc1706fbd6e2a5c0ee34a6f8de875aae20904c9f47e18c88d2fcb25d9ea1a79'
FLUTTER_MACOS_VERSION='3.19.0'
FLUTTER_MACOS_ARCHIVE='stable/macos/flutter_macos_3.19.0-stable.zip'
FLUTTER_MACOS_SHA256='e1504490fa8040de922daba21f4e689cf5b6e42f608d8be0c97435060ecd3924'
