# Autogenerated at 2024-01-26T22:48:55.382737
# Run _flutter_version_update.dart to update.

FLUTTER_URL='https://storage.googleapis.com/flutter_infra_release/releases/'
FLUTTER_WINDOWS_VERSION='3.16.9'
FLUTTER_WINDOWS_ARCHIVE='stable/windows/flutter_windows_3.16.9-stable.zip'
FLUTTER_WINDOWS_SHA256='90bade92aae819ee8b8a9c718c280b221ff0b7935e9fa6a284e7035e54e9fa21'
FLUTTER_LINUX_VERSION='3.16.9'
FLUTTER_LINUX_ARCHIVE='stable/linux/flutter_linux_3.16.9-stable.tar.xz'
FLUTTER_LINUX_SHA256='8868138a6f339f90353baefef0d789e06c3299d5f94db653decefda6633a9a8e'
FLUTTER_MACOS_VERSION='3.16.9'
FLUTTER_MACOS_ARCHIVE='stable/macos/flutter_macos_3.16.9-stable.zip'
FLUTTER_MACOS_SHA256='26b8db4cadb682cf5f535fb354e692517cf85ef6ccfd472f5686060386a89461'
