// Regenerates lib/utils/public_suffix_list.g.dart from publicsuffix.org.
//
// The list is vendored rather than fetched at runtime: the iOS AutoFill
// extension has no business making network requests while filling a password,
// and tests need to be deterministic. Run this every few months, and check the
// diff — entries do get removed, which can change which host is a registrable
// domain.
//
//   dart run _tools/update_public_suffix_list.dart
//
// The generated file keeps the `BEGIN PRIVATE` / `END PRIVATE` markers, because
// package:public_suffix uses them to tell ICANN rules from private ones.

import 'dart:io';

const _sourceUrl = 'https://publicsuffix.org/list/public_suffix_list.dat';
const _outputPath = 'lib/utils/public_suffix_list.g.dart';

Future<void> main() async {
  if (!File('pubspec.yaml').existsSync()) {
    stderr.writeln('run this from the authpass/ directory.');
    exit(1);
  }

  stdout.writeln('fetching $_sourceUrl');
  final client = HttpClient();
  final String body;
  try {
    final request = await client.getUrl(Uri.parse(_sourceUrl));
    final response = await request.close();
    if (response.statusCode != HttpStatus.ok) {
      stderr.writeln('unexpected status ${response.statusCode}');
      exit(1);
    }
    body = await response.transform(const SystemEncoding().decoder).join();
  } finally {
    client.close();
  }

  final lines = body.split(RegExp(r'\r?\n'));
  final kept = <String>[];
  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) {
      continue;
    }
    if (trimmed.startsWith('//')) {
      // section markers are load bearing, every other comment is not.
      if (trimmed.contains('BEGIN PRIVATE') ||
          trimmed.contains('END PRIVATE')) {
        kept.add(trimmed);
      }
      continue;
    }
    kept.add(trimmed);
  }

  if (kept.length < 5000) {
    stderr.writeln('only ${kept.length} rules parsed, that cannot be right.');
    exit(1);
  }
  if (!kept.any((line) => line.contains('BEGIN PRIVATE'))) {
    stderr.writeln('no private section marker found.');
    exit(1);
  }
  if (kept.any((line) => line.contains("'''"))) {
    stderr.writeln('a rule contains a dart string terminator.');
    exit(1);
  }

  final out = StringBuffer()
    ..writeln('// GENERATED BY _tools/update_public_suffix_list.dart')
    ..writeln('// DO NOT EDIT. Source: $_sourceUrl')
    ..writeln('//')
    ..writeln('// The Public Suffix List is licensed MPL 2.0.')
    ..writeln()
    ..writeln(
      "import 'package:string_literal_finder_annotations/"
      "string_literal_finder_annotations.dart';",
    )
    ..writeln()
    ..writeln('/// ${kept.length} rules, comments and blank lines stripped.')
    ..writeln('@NonNls')
    ..writeln("const publicSuffixListData = r'''")
    ..writeln(kept.join('\n'))
    ..writeln("''';");

  File(_outputPath).writeAsStringSync(out.toString());
  stdout.writeln('wrote ${kept.length} rules to $_outputPath');

  final format = await Process.run('dart', ['format', _outputPath]);
  if (format.exitCode != 0) {
    stderr.writeln('dart format failed: ${format.stderr}');
    exit(1);
  }
}
