# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:flutter_lints/flutter.yaml

analyzer:
#  FIXME: externalize / annotate all strings so this can be enabled.
  plugins:
    - string_literal_finder
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
  exclude:
    - lib/**/*.g.dart
    - test/**/*.mocks.dart

string_literal_finder:
  exclude_globs:
    - '_tools/**'
    - 'test_driver/**'
    - 'integration_test/**'
    - 'test/**'
    - '**/*.freezed.dart'

linter:
  rules:
    use_key_in_widget_constructors: false
    constant_identifier_names: false

    always_declare_return_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    unsafe_html: true

    always_put_control_body_on_new_line: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_slow_async_io: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    directives_ordering: true
    no_adjacent_strings_in_list: true
    package_api_docs: true
    prefer_asserts_in_initializer_lists: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true

