# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #upload_to_play_store(aab: '../build/app/outputs/bundle/release/app.aab', track: 'internal')
    upload_to_play_store(aab: '../build/app/outputs/bundle/release/app-release.aab', track: 'internal')
  end

end
