# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    debug

    #upload_to_play_store(aab: '../build/app/outputs/bundle/release/app.aab', track: 'internal')
    #upload_to_play_store(aab: '../build/app/outputs/bundle/release/app-release.aab', track: 'internal')

    upload_to_play_store(
        aab: '../build/app/outputs/bundle/playstoreRelease/app-playstore-release.aab',
        track: 'internal',
        metadata_path: 'ignoreme',
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_metadata: true
    )
  end

  lane :dev do
    debug

    upload_to_play_store(
      aab: '../build/app/outputs/bundle/playstoredevRelease/app-playstoredev-release.aab',
      track: 'internal',
      package_name: 'design.codeux.authpass.dev',
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata:  true
    )
  end
  # on the `beta` branch we will be pushing the dev release to public testing.
  lane :devbeta do
    debug

    upload_to_play_store(
      aab: '../build/app/outputs/bundle/playstoredevRelease/app-playstoredev-release.aab',
      track: 'beta',
      package_name: 'design.codeux.authpass.dev',
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata:  true
    )
  end
end
