name: Integration Tests

on:
  push:
  pull_request:
    branches:
      - master


jobs:

  drive_ios:

    runs-on: macos-latest

    strategy:
      matrix:
        device:
#          - "iPhone 8 (13.1)"
          - "iPhone .* Pro Max "

      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
#    - name: Postdeploy
#      env:
#        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
#      run: authpass/_tools/postdeploy.sh
    - name: ci-install-deps
      env:
        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
      run: "./authpass/_tools/ci-install-deps.sh ios"
    - name: List all simulators
      run: xcrun instruments -s
    # get UUID  simulator and boot a simulator on mac from  command line
    - name: Start Simulator
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 ~ device { print $2 }' | head -n 1
        )
        echo starting ${UDID}
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
    - name: run test integration_test
      run: "cd authpass && ~/deps/flutter/bin/flutter test integration_test"
#    - uses: actions/upload-artifact@v1
#      with:
#        name: driver-screenshots
#        path: authpass/build/screenshots

