name: build linux

on: 
  push:
    branches:
      - 'linux**'
      - 'stable'
      - 'beta'

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        flavor: ['linux']

      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Postdeploy
      env:
        BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
      run: authpass/_tools/postdeploy.sh
    - run: |
        sudo apt-get update
        sudo apt-get install -y \
        clang \
        cmake \
        ninja-build \
        file pkg-config git unzip \
        libgtk-3-dev libx11-dev \
        libsecret-1-dev \
        keybinder-3.0
    - name: ci-install-deps
      run: "./authpass/_tools/ci-install-deps.sh linux"
#    - run: ~/deps/flutter/bin/flutter channel master && ~/deps/flutter/bin/flutter upgrade && ~/deps/flutter/bin/flutter config --enable-linux-desktop
    - run: ~/deps/flutter/bin/flutter config --enable-linux-desktop
    - name: build ${{ matrix.flavor }} apk
      id: buildapk
      env:
        GIT_AUTHOR_NAME: 'Github Action CI'
        GIT_AUTHOR_EMAIL: 'herbert.github.ci@codeux.design'
        GIT_COMMITTER_NAME: 'Github Action CI'
        GIT_COMMITTER_EMAIL: 'herbert.github.ci@codeux.design'
      run: "./authpass/_tools/ci-release.sh ${{ matrix.flavor }}"
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.buildapk.outputs.outputfilename }}
        path: authpass/${{ steps.buildapk.outputs.outputpath }}
    - name: upload artifact
      run: ./authpass/_tools/upload-artifact.sh authpass/${{ steps.buildapk.outputs.outputpath }}
    - uses: snapcore/action-build@v1
      id: snapcraft
    - name: upload snap artifact
      run: |
        curl --request POST \
          --url https://data.authpass.app/data/artifact.push \
          --fail \
          --form token=$( cat authpass/_tools/secrets/artifact_token.txt ) \
          --form upload=@${{ steps.snapcraft.outputs.snap }} \
          --form filename=authpass_${{ steps.buildapk.outputs.appversion }}_${{ steps.buildapk.outputs.appbuildnumber }}_amd64.snap
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAPCRAFT_TOKEN }}
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: edge
    - uses: actions/upload-artifact@v2
      with:
        name: authpass-${{ steps.buildapk.outputs.appversion }}_${{ steps.buildapk.outputs.appbuildnumber }}-snap
        path: ${{ steps.snapcraft.outputs.snap }}
